# Generated by Django 3.2.25 on 2024-10-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_no', models.BigIntegerField()),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('age', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer_registration',
                'managed': False,
            },
        ),
    ]
