# Generated by Django 3.2.25 on 2024-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplycoProduct',
            fields=[
                ('supplycoproduct_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplycoproduct_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(db_column='expiry date')),
                ('manufacture_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('actual_price', models.IntegerField()),
                ('available_price', models.IntegerField()),
            ],
            options={
                'db_table': 'supplyco_product',
                'managed': False,
            },
        ),
    ]
