# Generated by Django 3.2.25 on 2024-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
