# Generated by Django 3.2.25 on 2024-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationProduct',
            fields=[
                ('rationproduct_id', models.AutoField(db_column='Rationproduct_id', primary_key=True, serialize=False)),
                ('card_type', models.CharField(max_length=12)),
                ('card_color', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit', models.CharField(max_length=20)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ration_product',
                'managed': False,
            },
        ),
    ]
