# Generated by Django 3.2.25 on 2024-09-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.BigIntegerField()),
                ('card_type', models.CharField(max_length=10)),
                ('card_color', models.CharField(max_length=10)),
                ('head_name', models.CharField(max_length=45)),
                ('annual_income', models.IntegerField()),
                ('occupation', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('no_of_family_member', models.IntegerField()),
                ('no_of_adults', models.IntegerField()),
                ('no_of_family_children', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
