# Generated by Django 3.2.25 on 2024-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('rationproduct_id', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('stock_price', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
